#!/bin/bash
# vimsane-update-3
#
# Updates a user's configuration to vimsane v3
#
# Prerequisites:  The ~/.vim directory must NOT exist yet.  
#                 (We're going to fetch it from github)
#
# Args:  
#      $1: version currently installed [ '0' if not previously installed ]
#      $2: target version.  Must be >= ThisVersion.

source ${VimsaneCodeRoot}/vs_constants
ThisVersion=3

function errExit { 
   echo  "ERROR: $*" >&2
   exit 1
}

cd ${HOME}
[[ -d $HOME/.vim ]] && errExit ".vim already exists, vimsane-update-3 failed."
vs_github_clone "sanekits/vimsane-cfg" .vim || exit 1

cd ~/.vim || errExit "Step3.0x011189"

templ="template-vimrc-vimsane-1"  # Our initial vimrc for a new user

[[ -f vimrc ]] && errExit "Unexpected $VIM/vimrc was found.  Please rename this and move it out of ~/.vim"

[[ -f .vimrc ]] && errExit "Unexpected $VIM/.vimrc was found.  Please rename this and move it out of ~/.vim"

echo "Creating ~/.vim/vimrc from ${templ}:"
/bin/cp $templ vimrc || errExit "Step3.0x92452"


echo "Update to v$ThisVersion is complete."


