#!/bin/bash
# vimsane-update-1
#
# Updates a user's configuration to vimsane v1
#
# Prerequisite:  the ~/.vimsane directory must exist 
#
# Args:  
#      $1: version currently installed [ '0' if not previously installed ]
#      $2: target version.  Must be >= ThisVersion.

source ${VimsaneCodeRoot}/vs_constants
ThisVersion=1

function errExit { 
   echo  "ERROR: $*" >&2
   exit 1
}

function safeToInitVimrc {
    if [[ -f ~/.vimrc ]] || [[ -h ~/.vimrc ]]; then  
        prompt_flow "ERROR: Vimsane setup found ~/.vimrc.  This is not allowed.  If you want to keep it, do this:

        1.  Rename your ~/.vimrc to something else. 
        2.  Install vimsane
        3.  Edit the new ~/.vim/vimrc that vimsane creates, and add your stuff to it.
        "
        false
        return
    fi
    if cd $HOME/.vim; then
        prompt_flow "ERROR: Vimsane setup found an existing ~/.vim directory.  This is not allowed.  If you want to keep it:

        1. Rename ~/.vim to something else.
        2. Install vimsane
        3. Merge your stuff into the ~/.vim directory that vimsane creates.
        "
        false
        return
    fi
    true
}

if [[ -z $sourceMe ]]; then
    if ! safeToInitVimrc; then
        exit 1
    fi
    echo "Update to v$ThisVersion complete."
    true
fi
# vim: filetype=sh formatoptions=ocr :
