#!/bin/bash
# vimsane-update-3
#
# Updates a user's configuration to vimsane v3
#
# Prerequisite:  the ~/.vimsane directory must exist 
#
# Args:  
#      $1: version currently installed [ '0' if not previously installed ]
#      $2: target version.  Must be >= ThisVersion.

source /bbsrc/training/vimsane/vs_constants
ThisVersion=3

function errExit { 
   echo  "ERROR: $*" >&2
   exit 1
}
echo ""
